[package]
name = "axdtb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
fdt = "0.1.4"
bitflags = "2.3.0"
zerocopy = { version = "0.7.5", features = ["derive"] }